/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalTerminalIdRouteImport } from './routes/terminal.$terminalId'
import { Route as ThreadThreadIdRouteImport } from './routes/thread.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalTerminalIdRoute = TerminalTerminalIdRouteImport.update({
  id: '/terminal/$terminalId',
  path: '/terminal/$terminalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadThreadIdRoute = ThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terminal/$terminalId': typeof TerminalTerminalIdRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminal/$terminalId': typeof TerminalTerminalIdRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terminal/$terminalId': typeof TerminalTerminalIdRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/terminal/$terminalId' | '/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/terminal/$terminalId' | '/thread/$threadId'
  id: '__root__' | '/' | '/terminal/$terminalId' | '/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TerminalTerminalIdRoute: typeof TerminalTerminalIdRoute
  ThreadThreadIdRoute: typeof ThreadThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/$terminalId': {
      id: '/terminal/$terminalId'
      path: '/terminal/$terminalId'
      fullPath: '/terminal/$terminalId'
      preLoaderRoute: typeof TerminalTerminalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$threadId': {
      id: '/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TerminalTerminalIdRoute: TerminalTerminalIdRoute,
  ThreadThreadIdRoute: ThreadThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
